#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/functions"

case "$1" in
  letsencrypt:add)
    [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
    verify_app_name "$2"
    APP="$2"; DOMAIN="$3";

    mkdir -p "$DOKKU_ROOT/$APP/tls"
    sudo docker run -it --rm -p 443:443 -p 80:80 --name letsencrypt \
            -v "/etc/letsencrypt:/etc/letsencrypt" \
            -v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
            quay.io/letsencrypt/letsencrypt:latest --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory -d $DOMAIN auth

    sudo cp "/etc/letsencrypt/live/$DOMAIN/privkey.pem" "$DOKKU_ROOT/$APP/tls/server.key"
    sudo cp "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" "$DOKKU_ROOT/$APP/tls/server.crt"
    sudo chown -hR dokku:dokku "$DOKKU_ROOT/$APP/tls/"
    nginx_build_config $APP
    ;;
  help | letsencrypt:help)
    cat && cat<<EOF
    letsencrypt:add <app> <domain>, generate certificate for <domain> and configure nginx with it"
EOF
    ;;
  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;
esac
